"""Task Repository 인터페이스."""

from __future__ import annotations

from typing import Protocol

from iris.domain.task.models import Plan, PlanStep, Task, TaskCheckpoint, TaskResult
from iris.domain.task.enums import TaskStatus


class TaskRepository(Protocol):
    """Task 영속."""

    def save(self, task: Task) -> None: ...
    def get_by_id(self, task_id: str) -> Task | None: ...
    def update(self, task: Task) -> None: ...
    def get_active(self) -> list[Task]: ...


class PlanRepository(Protocol):
    """Plan·PlanStep 영속."""

    def save_plan(self, plan: Plan) -> None: ...
    def get_plan(self, plan_id: str) -> Plan | None: ...
    def get_latest_plan_for_task(self, task_id: str) -> Plan | None: ...
    def save_step(self, step: PlanStep) -> None: ...
    def get_steps(self, plan_id: str) -> list[PlanStep]: ...
    def get_step(self, step_id: str) -> PlanStep | None: ...
    def update_step(self, step: PlanStep) -> None: ...


class CheckpointRepository(Protocol):
    """TaskCheckpoint 영속."""

    def save(self, checkpoint: TaskCheckpoint) -> None: ...
    def get_latest_for_task(self, task_id: str) -> TaskCheckpoint | None: ...
    def get_by_id(self, checkpoint_id: str) -> TaskCheckpoint | None: ...


class TaskResultRepository(Protocol):
    """TaskResult 영속."""

    def save(self, result: TaskResult) -> None: ...
    def get_by_task_id(self, task_id: str) -> TaskResult | None: ...
